# Generated by Django 2.1.4 on 2018-12-19 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteorite_landings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meteoritelanding',
            options={'managed': False, 'ordering': ['country_area', 'meteorite_class'], 'verbose_name': 'Meteorite Landing', 'verbose_name_plural': 'Meteorite Landings'},
        ),
    ]
